### ISSUE TITLE
As a user I shall not be able to give negative values as metrics values

### ISSUE THREAD

**Issue by StarSovu** [ohtu2021-kvantti/WebMark#57]
Currently there is no check if given values are negative. (Iterations, Measurement, Circuit depth, Accuracy)

**Comment by tapanih** [comment]
There is also no check that the values are numeric until it hits the database causing an internal server error. The only safe guard is the HTML form that is easily edited.

**Comment by lambdakilo** [comment]
> There is also no check that the values are numeric until it hits the database causing an internal server error. The only safe guard is the HTML form that is easily edited.

Does this mean there should be a custom error page if the user manipulates the html and inserts text to metrics causing an internal server error?

**Comment by tapanih** [comment]
> > There is also no check that the values are numeric until it hits the database causing an internal server error. The only safe guard is the HTML form that is easily edited.
> 
> Does this mean there should be a custom error page if the user manipulates the html and inserts text to metrics causing an internal server error?

A simple redirect to main page should be fine. Preventing anyone from causing errors is the important part here.
EDIT: what you are doing right now is fine.

**Comment by vuorenkoski** [comment]
I made a solution inwhich http request resturns statuscode 400 and simple explanation. What you guys think?

**Comment by StarSovu** [comment]
Seems like a good simple solution. Should we ask our customer how they want to handle this?
