### ISSUE TITLE
An error is printed to the console when algorithms do not have common molecules

### ISSUE THREAD

**Issue by tapanih** [ohtu2021-kvantti/WebMark#81]
There is a small bug in the comparison view. When two algorithms do not have common molecules, a following error is printed to the console:
`Uncaught (in promise) Error: Argument given to addRows must be either a number or an array`

Note that the comparison view needs to be overhauled to support comparing molecules instead of just algorithms. Changes are probably also needed when real data is available.

**Comment by lambdakilo** [comment]
![image](https://user-images.githubusercontent.com/31825085/115350075-4e54c000-a1bd-11eb-8670-accc40fcd092.png)
@tapanih are there any particular example algorithms that print the error to any console?
